name: daelim_2025
description: "2025년도 3학년 1학기 모바일앱프로그래밍 언어 수업 프로젝트"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
